"""add table Brand

Revision ID: 63051e8ef27d
Revises: 
Create Date: 2022-07-03 22:46:26.179743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63051e8ef27d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brand')
    # ### end Alembic commands ###
